CREATE TABLE [dbo].[Personnage]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Nom VARCHAR(50) NOT NULL,
	Race VARCHAR(20) NOT NULL,
	Force INT NOT NULL,
	Endurance INT NOT NULL,
	PV INT NOT NULL
	CONSTRAINT CK_PV CHECK (PV > 0)
)
